[build]
  command = "nuxt build"
  publish = "dist"

[functions]
  directory = ".output/server/functions"

[build.environment]
  NODE_VERSION = "24.0.2"
  NPM_VERSION = "11.3.0"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
